# 2016 DATASET 35800. pb-1

In [1]:
import pandas as pd
from collections import OrderedDict
import os, multiprocessing, sys
from IPython.display import display, HTML
pd.set_option('display.max_colwidth',10000)
cwd=os.getcwd()
sys.path.append(cwd+"/Utils/")

from drawUtils import *
from variables import *
from selections_SSLep import *
from samplesVH import *

Welcome to JupyROOT 6.12/06

# Dataset

In [2]:
LUMI        = 35800. # pb-1
ALLTABLE={}
processes = [ "ttV" , "WW" ,"WZ" , "TTbar-SL", "ST", "TTbar-DiLep", "WJetsToLNu" , "DYJetsToLL" , "data_obs" ]
for TAG in processes:
    TABLE=[]
    for num, bkgs in enumerate(samples['%s' %TAG]['files']):
        #print num, bkgs
        TABLE.append(OrderedDict({
            'Process': TAG,
            'files' : bkgs,
            'Events Number' : sample[bkgs]['nevents'],
            'Cross Section' : sample[bkgs]['xsec']
                 }))
    ALLTABLE[TAG]=pd.DataFrame(TABLE)
    
for table in ALLTABLE:
    display(ALLTABLE[table])

,Process,files,Events Number,Cross Section
0,WZ,WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8-v1,11887460,4.4

,Process,files,Events Number,Cross Section
0,TTbar-SL,TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1-v1,50016940,180.990976
1,TTbar-SL,TTJets_SingleLeptFromTbar_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1-v1,48266350,180.990976

,Process,files,Events Number,Cross Section
0,WJetsToLNu,WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v1,21978040,61530

,Process,files,Events Number,Cross Section
0,TTbar-DiLep,TTJets_DiLept_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1-v1,23637880,92.417778

  Process                                  files  Events Number  Cross Section
0      WW  WW_TuneCUETP8M1_13TeV-pythia8_ext1-v1        7981136            118

,Process,files,Events Number,Cross Section
0,data_obs,METRun2016B-03Feb2017_ver2-v2,35987712,1.0
1,data_obs,METRun2016C-03Feb2017-v1,17381222,1.0
2,data_obs,METRun2016D-03Feb2017-v1,20947429,1.0
3,data_obs,METRun2016E-03Feb2017-v1,22348402,1.0
4,data_obs,METRun2016F-03Feb2017-v1,13319829,1.0
5,data_obs,METRun2016G-03Feb2017-v1,26974131,1.0
6,data_obs,METRun2016H-03Feb2017_ver2-v1,38957320,1.0
7,data_obs,METRun2016H-03Feb2017_ver3-v1,816165,1.0
8,data_obs,SingleMuonRun2016B-03Feb2017_ver1-v1,2789243,1.0
9,data_obs,SingleMuonRun2016B-03Feb2017_ver2-v2,158145722,1.0
10,data_obs,SingleMuonRun2016C-03Feb2017-v1,67441308,1.0
11,data_obs,SingleMuonRun2016D-03Feb2017-v1,98017996,1.0
12,data_obs,SingleMuonRun2016E-03Feb2017-v1,90984718,1.0
13,data_obs,SingleMuonRun2016F-03Feb2017-v1,65425108,1.0
14,data_obs,SingleMuonRun2016G-03Feb2017-v1,149916849,1.0
15,data_obs,SingleMuonRun2016H-03Feb2017_ver2-v1,171134793,1.0
16,data_obs,SingleMuonRun2016H-03Feb2017_ver3-v1,4393222,1.0
17,data_obs,SingleElectronRun2016B-03Feb2017_ver1-v1,1422819,1.0
18,data_obs,SingleElectronRun2016B-03Feb2017_ver2-v2_1,246440440,1.0
19,data_obs,SingleElectronRun2016B-03Feb2017_ver2-v2,246440440,1.0
20,data_obs,SingleElectronRun2016C-03Feb2017-v1,97259854,1.0
21,data_obs,SingleElectronRun2016D-03Feb2017-v1,148167727,1.0
22,data_obs,SingleElectronRun2016E-03Feb2017-v1,117321545,1.0
23,data_obs,SingleElectronRun2016F-03Feb2017-v1,70593532,1.0
24,data_obs,SingleElectronRun2016G-03Feb2017-v1,153363109,1.0
25,data_obs,SingleElectronRun2016H-03Feb2017_ver2-v1,126863489,1.0
26,data_obs,SingleElectronRun2016H-03Feb2017_ver3-v1,3191585,1.0
27,data_obs,DoubleMuonRun2016B-03Feb2017_ver2-v2,82535526,1.0
28,data_obs,DoubleMuonRun2016D-03Feb2017-v1,33861745,1.0
29,data_obs,DoubleMuonRun2016F-03Feb2017-v1,20329921,1.0
30,data_obs,DoubleMuonRun2016H-03Feb2017_ver2-v1,47693168,1.0
31,data_obs,DoubleMuonRun2016C-03Feb2017-v1,27934629,1.0
32,data_obs,DoubleMuonRun2016E-03Feb2017-v1,28246946,1.0
33,data_obs,DoubleMuonRun2016G-03Feb2017-v1,45235604,1.0
34,data_obs,DoubleMuonRun2016H-03Feb2017_ver3-v1,1219644,1.0

,Process,files,Events Number,Cross Section
0,ST,ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1-v1,1000000.0,3.45
1,ST,ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1-v1,5922361.0,27.10
2,ST,ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1-v1,11108070.0,27.10
3,ST,ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M2T4-v1,5435134.0,20.00
4,ST,ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M2T4-v1,5372991.0,20.00

,Process,files,Events Number,Cross Section
0,DYJetsToLL,DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8-v1,26156930,9000.0
1,DYJetsToLL,DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1-v2,49144270,6025.0

,Process,files,Events Number,Cross Section
0,ttV,TTWJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8_ext1-v3,236047,0.2040
1,ttV,TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8_ext1-v1,1115478,0.2530
2,ttV,ttHToNonbb_M125_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8-v1,3389728,0.0546

# Selections

In [3]:
ALLTABLE2={}
TABLE1=[]
#Selection=['OSSF','OSOF','SSSF','SSOF']
for sel in selection:
    TABLE1.append(OrderedDict({
        'Selection Region' : sel,
        'Description' : selection[sel]
    }))

ALLTABLE2=pd.DataFrame(TABLE1)
display(ALLTABLE2)

,Selection Region,Description
0,OSemu,(( (HLT_IsoMu22 || HLT_IsoMu22_eta2p1 || HLT_IsoTkMu22_eta2p1 || HLT_IsoMu24 || HLT_IsoTkMu24 || HLT_Mu45_eta2p1 || HLT_Mu50) ) && ( (( 1==1 ) && ( (Muon_charge[0]!=Electron_charge[0]) && Muon_pt[0]>27 && Electron_pt[0]>25 && Muon_pfRelIso03_all[0]<0.1 && Muon_mediumId[0]>0 && Electron_cutBased[0]>0 && Electron_pfRelIso03_all[0]<0.1 )) ))
1,SSmumu2b,(( (HLT_IsoMu22 || HLT_IsoMu22_eta2p1 || HLT_IsoTkMu22_eta2p1 || HLT_IsoMu24 || HLT_IsoTkMu24 || HLT_Mu45_eta2p1 || HLT_Mu50) ) && ( (( 1==1 ) && ( (Muon_charge[0]==Muon_charge[1]) && Muon_pt[0]>25 && Muon_pt[1]>15 && Muon_pfRelIso03_all[0]<0.1 && Jet_btagCSVV2[1]>0.8 )) ))
2,Trigger,(( (HLT_IsoMu22 || HLT_IsoMu22_eta2p1 || HLT_IsoTkMu22_eta2p1 || HLT_IsoMu24 || HLT_IsoTkMu24 || HLT_Mu45_eta2p1 || HLT_Mu50) ) && ( 1==1 ))
3,OSmumu,(( (HLT_IsoMu22 || HLT_IsoMu22_eta2p1 || HLT_IsoTkMu22_eta2p1 || HLT_IsoMu24 || HLT_IsoTkMu24 || HLT_Mu45_eta2p1 || HLT_Mu50) ) && ( (( 1==1 ) && ( (Muon_charge[0]!=Muon_charge[1]) && Muon_pt[0]>17 && Muon_pt[1]>8 && Muon_mediumId[0]>0 && Muon_mediumId[1]>0 && Muon_pfRelIso03_all[0]<0.15 && Muon_pfRelIso03_all[1]<0.15 )) ))
4,SSmumu,(( (HLT_IsoMu22 || HLT_IsoMu22_eta2p1 || HLT_IsoTkMu22_eta2p1 || HLT_IsoMu24 || HLT_IsoTkMu24 || HLT_Mu45_eta2p1 || HLT_Mu50) ) && ( (( 1==1 ) && ( (Muon_charge[0]==Muon_charge[1]) && Muon_pt[0]>25 && Muon_pt[1]>15 && Muon_pfRelIso03_all[0]<0.1 )) ))
5,SSmumu1b,(( (HLT_IsoMu22 || HLT_IsoMu22_eta2p1 || HLT_IsoTkMu22_eta2p1 || HLT_IsoMu24 || HLT_IsoTkMu24 || HLT_Mu45_eta2p1 || HLT_Mu50) ) && ( (( 1==1 ) && ( (Muon_charge[0]==Muon_charge[1]) && Muon_pt[0]>25 && Muon_pt[1]>15 && Muon_pfRelIso03_all[0]<0.1 && Jet_btagCSVV2[0]>0.8 )) ))
6,DiLepTT,"(( (( (HLT_IsoMu22 || HLT_IsoMu22_eta2p1 || HLT_IsoTkMu22_eta2p1 || HLT_IsoMu24 || HLT_IsoTkMu24 || HLT_Mu45_eta2p1 || HLT_Mu50) ) && ( (( 1==1 ) && ( Muon_pt[0]>24 && Electron_pt[0]>20 )) )) ) && ( invariantMass(Electron_pt[0], Electron_eta[0], Electron_phi[0], Electron_mass[0], Muon_pt[0], Muon_eta[0], Muon_phi[0], Muon_mass[0])>15 ))"
7,OSee,(( (HLT_Ele25_WPTight_Gsf || HLT_Ele27_eta2p1_WPLoose_Gsf || HLT_Ele105_CaloIdVT_GsfTrkIdT) ) && ( (( 1==1 ) && ( (Electron_charge[0]!=Electron_charge[1]) && Electron_pt[0]>25 && Electron_pt[1]>17 && Electron_pfRelIso03_all[0]<0.15 && Electron_pfRelIso03_all[1]<0.15 )) ))

# Variables